default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: hitched
  password: uns3cur3
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: hitched_development

test:
  <<: *default
  database: hitched_test
